### ISSUE TITLE
Fix Token tests

### ISSUE THREAD

**Issue by llunaCreixent** [CirclesUBI/circles-core#120]
Token Tests started to fail only in GitHub Actions with this PR: https://github.com/CirclesUBI/circles-core/pull/119
See the logs from https://github.com/CirclesUBI/circles-core/runs/6858140027?check_suite_focus=true:
```
> @circles/core@2.11.1-prerelease-5b905db test /home/runner/work/circles-core/circles-core/circles-core
> jest --runInBand
cat: edges-data/edges.json: No such file or directory
FAIL test/token.test.js (358.495 s)
  ● Token › Find transitive transfer steps › should return max flow and possible path
    TransferError: Request failed @ http://api.circles.local/api/transfers/ with error 503
      54 |     return response.data;
      55 |   } catch (error) {
    > 56 |     throw new TransferError(error.message, ErrorCodes.UNKNOWN_ERROR);
         |           ^
      57 |   }
      58 | }
      59 |
      at _callee13$ (src/token.js:56:11)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:294:22)
      at Generator.throw (node_modules/regenerator-runtime/runtime.js:119:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _throw (node_modules/@babel/runtime/helpers/asyncToGenerator.js:29:9)
          at runMicrotasks (<anonymous>)
  ● Token › Transitive Transactions › should send Circles to someone transitively
    TransferError: Request failed @ http://api.circles.local/api/transfers/ with error 503
      54 |     return response.data;
      55 |   } catch (error) {
    > 56 |     throw new TransferError(error.message, ErrorCodes.UNKNOWN_ERROR);
         |           ^
      57 |   }
      58 | }
      59 |
      at _callee13$ (src/token.js:56:11)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:294:22)
      at Generator.throw (node_modules/regenerator-runtime/runtime.js:119:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _throw (node_modules/@babel/runtime/helpers/asyncToGenerator.js:29:9)
          at runMicrotasks (<anonymous>)
  ● Token › Transitive Transactions › should fail sending Circles when data error
    Command failed: docker exec circles-api cat edges-data/edges.json
    cat: edges-data/edges.json: No such file or directory
      315 |       await Promise.resolve().then(() => {
      316 |         const edgesData = JSON.parse(
    > 317 |           execSync(
          |           ^
      318 |             `docker exec circles-api cat edges-data/edges.json`,
      319 |           ).toString(),
      320 |         );
      at test/token.test.js:317:11
          at runMicrotasks (<anonymous>)
PASS test/common.test.js
PASS test/safe.test.js (134.65 s)
PASS test/activity.test.js (89.094 s)
PASS test/trust.test.js (89.627 s)
PASS test/organization.test.js (155.172 s)
PASS test/utils.test.js (32.205 s)
PASS test/user.test.js
PASS test/lib.test.js
Test Suites: 1 failed, 8 passed, 9 total
Tests:       3 failed, 54 passed, 57 total
Snapshots:   0 total
Time:        865.09 s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @circles/core@2.11.1-prerelease-5b905db test: `jest --runInBand`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @circles/core@2.11.1-prerelease-5b905db test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-06-13T09_38_59_875Z-debug.log
Error: Process completed with exit code 1.
```

**Comment by llunaCreixent** [comment]
Let's check first removing the the new test `Token › Transitive Transactions › should fail sending Circles when data error`
